#!/usr/bin/env python

import os
import sys
from transformers import AutoModelForCausalLM, AutoTokenizer

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_NAME, MODEL_CACHE, TOKEN_CACHE

# Make cache folder
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)
if not os.path.exists(TOKEN_CACHE):
    os.makedirs(TOKEN_CACHE)

tokenizer = AutoTokenizer.from_pretrained(
   MODEL_NAME,
   trust_remote_code=True,
)
tokenizer.save_pretrained(TOKEN_CACHE)

model = AutoModelForCausalLM.from_pretrained(
   MODEL_NAME,
   trust_remote_code=True,
)
model.save_pretrained(MODEL_CACHE)